server
{
    listen 80;
    server_name simuler.cn;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /www/wwwroot;
    }

    location / {
        return 301 https://simuler.cn$request_uri;
    }
}

server
{
    listen 443 ssl;
    listen 443 quic;
    http2 on;
    server_name simuler.cn;

    ssl_certificate      /www/server/panel/vhost/ssl/simuler.cn/fullchain.pem;
    ssl_certificate_key  /www/server/panel/vhost/ssl/simuler.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    add_header Alt-Svc 'quic=":443"; h3=":443"; h3-29=":443"; h3-27=":443";h3-25=":443"; h3-T050=":443"; h3-Q050=":443";h3-Q049=":443";h3-Q048=":443"; h3-Q046=":443"; h3-Q043=":443"';
    error_page 497 https://$host$request_uri;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    access_log  /www/wwwlogs/simuler.cn.log;
    error_log   /www/wwwlogs/simuler.cn.error.log;
}
